name: primamethyl
version: 0.1.0
config-version: 2

profile: primamethyl

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  primamethyl:
    +database: "{{ env_var('DBT_DUCKDB_DATABASE') }}"
    staging:
      +materialized: view
    marts:
      +materialized: view
