name: primamenthyl
version: 0.1.0
config-version: 2

profile: primamenthyl

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  primamenthyl:
    +database: "{{ env_var('DBT_DUCKDB_DATABASE') }}"
    staging:
      +materialized: table
    marts:
      +materialized: table
